runtime: nodejs20

env_variables:
  JWT_SECRET: aFa2ou4z8CkYFdZ
  FIRESTORE_PROJECT_ID: lightbells-watch-party

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /socket.io/.*
  script: auto
  secure: always

- url: /.*
  script: auto
  secure: always

network:
  session_affinity: true
